sidebar:
  catalog: Catalog
  have_read: You've read

footer:
  driven: Driven
  theme: Theme

copy:
  success: Copy successfully
  error: Copy error
  noSupport: The browser does not support

page:
  articles: Articles
  tag: Tag
  category: Category
  archives: Archives

sticky: Sticky
no_title: No title
archives: Archives

post:
  created: Created
  updated: Updated
  wordcount: Word count
  min2read: "Reading time: %s min"
  page_pv: Post View
  copyright:
    author: Author
    link: Link
    copyright_notice: Copyright Notice
    copyright_content: 'All articles in this blog are licensed under <a href="%s">%s</a> unless stating additionally.'

search: Search
algolia_search:
  input_placeholder: Search for Posts
  hits_empty: "We didn't find any results for the search: ${query}."
  hits_stats: "${hits} results found in ${time} ms"

local_search:
  label: Local search
  input_placeholder: Search for Posts
  hits_empty: "We didn't find any results for the search: ${query}"
  powered_by: Powered by

pagination:
  prev: Previous Post
  next: Next Post

comment: Comment

aside:
  articles: Articles
  tags: Tags
  categories: Categories
  card_announcement: Announcement
  card_categories: Categories
  card_tags: Tags
  card_archives: Archives
  card_recent_post: Recent Post
  card_bookmark: Add to bookmark
  card_webinfo:
    headline: Info
    article_name: Article
    runtime_name: Run time
    site_uv_name: UV
    site_pv_name: PV

donate: Donate
share: Share

bookmark:
  title: Bookmark


rightside:
  readmode_title: Read Mode
  font_plus_title: Increase font size
  font_minus_title: Decrease font size
  translate_title: Traditional Chinese and Simplified Chinese Conversion
  night_mode_title: Dark Mode
  back_to_top: Back to top
  toc: Table of Contents
  scroll_to_comment: Scroll to comment
  setting: Setting

runtime_unit: days

copy_copyright:
  author: Author
  link: Link
  source: Source
  info: Copyright is owned by the author. For commercial reprints, please contact the author for authorization. For non-commercial reprints, please indicate the source.

Snackbar:
  bookmark:
    message_prev: Press
    message_next: to bookmark this page
  chs_to_cht: Traditional Chinese Activated Manually
  cht_to_chs: Simplified Chinese Activated Manually
  day_to_night: Light Mode Activated Manually
  night_to_day: Dark Mode Activated Manually
